#!/bin/bash - 
#===============================================================================
#
#          FILE: newvimrc.sh
# 
#         USAGE: ./newvimrc.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: tongl (), 
#  ORGANIZATION: 
#       CREATED: 2013年07月12日 17时20分46秒 CST
#      REVISION:  ---
#===============================================================================

cp ~/.vimrc ~/.vim/vimrc_bk

