#!/bin/bash - 
#===============================================================================
#
#          FILE: newvimrc.sh
# 
#         USAGE: ./newvimrc.sh 
#        AUTHOR: tongl (), 
#  ORGANIZATION: 
#       CREATED: 2013年07月12日 17时20分46秒 CST
#      REVISION:  ---
#===============================================================================


if [ "$1" = "w" ] ; then
    cp ~/.vimrc ~/.vim/vimrc_bk_work
    echo "ok"
elif [ "$1" = "h" ] ; then
    cp ~/.vimrc ~/.vim/vimrc_bk
    echo "ok"
else 
    echo "USAGE w h"
fi
